// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/analyze": {
            "post": {
                "description": "Analyzes a web page based on the URL provided in the form submission",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "Analysis"
                ],
                "summary": "Analyze a web page from form submission",
                "parameters": [
                    {
                        "type": "string",
                        "description": "URL of the web page to analyze",
                        "name": "url",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.AnalysisResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.APIError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "models.AnalysisResult": {
            "type": "object",
            "properties": {
                "analysis_time": {
                    "description": "Changed from time.Duration to string",
                    "type": "string",
                    "example": "1.234s"
                },
                "error": {
                    "type": "string",
                    "example": "Failed to fetch page"
                },
                "external_links": {
                    "type": "integer",
                    "example": 2
                },
                "has_login_form": {
                    "type": "boolean",
                    "example": true
                },
                "headings": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "html_version": {
                    "type": "string",
                    "example": "HTML5"
                },
                "http_status_code": {
                    "type": "integer",
                    "example": 200
                },
                "inaccessible_links": {
                    "type": "integer",
                    "example": 0
                },
                "internal_links": {
                    "type": "integer",
                    "example": 5
                },
                "page_title": {
                    "type": "string",
                    "example": "Example Page"
                },
                "timestamp": {
                    "type": "string",
                    "example": "2023-01-01T12:00:00Z"
                },
                "url": {
                    "type": "string",
                    "example": "https://example.com"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Web Page Analyzer API",
	Description:      "A web service that analyzes web pages and provides detailed information about their structure, links, and forms.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
